# Generated by Django 4.1.4 on 2023-04-22 18:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('idnumber', models.IntegerField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('FREELANCER', 'FREELANCER'), ('CLIENT', 'CLIENT')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hair', 'Hair'), ('skin care', 'skin care'), ('Makeup Artist', 'Makeup Artist'), ('dressmaker', 'dressmaker')], max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('working_hours', models.IntegerField(default=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(db_index=True, max_length=100)),
                ('durations', models.FloatField(default=1)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewe_text', models.CharField(max_length=500)),
                ('stars', models.IntegerField(default=0)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='accounts.account')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('canceled', 'canceled'), ('waiting', 'waiting')], default='waiting', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
                ('note', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='accounts.account')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_order', to='accounts.account')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id', to='accounts.services')),
            ],
        ),
    ]
