# Generated by Django 4.1.4 on 2023-04-23 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.account')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to='accounts.freelancer')),
            ],
        ),
    ]
