# Generated by Django 4.1.4 on 2023-04-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_account', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='client',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers_clients', to='accounts.freelancer'),
        ),
    ]
