# Generated by Django 4.1.4 on 2023-04-23 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_account_alter_client_freelancer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.account'),
        ),
    ]
