# Generated by Django 4.1.4 on 2023-12-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='container',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='freelancer',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='clients',
            name='freelancer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers_clients', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='accounts.clients'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.clients'),
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
