# Generated by Django 4.1.4 on 2023-12-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
