# Generated by Django 4.1.4 on 2023-12-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewee',
            new_name='account',
        ),
    ]
