# Generated by Django 4.1.4 on 2023-12-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_payment_amount_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
    ]
