# Generated by Django 4.1.4 on 2023-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_start_time_order_time_remove_order_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='freelancer_id',
        ),
    ]
