# Generated by Django 4.1.4 on 2023-12-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_clients_freelancer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
    ]
