# Generated by Django 4.1.4 on 2023-12-06 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_clients_email_clients_phone_clients_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='clients',
            name='numberOfVist',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
