# Generated by Django 4.1.4 on 2023-12-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_time_order_date_clients_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
