# Generated by Django 4.1.4 on 2023-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_clients_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='numberOfVist',
            new_name='numberOfOrders',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('canceled', 'canceled'), ('waiting', 'waiting')], default='waiting', max_length=50),
        ),
    ]
