# Generated by Django 4.1.4 on 2023-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quntity',
            field=models.IntegerField(default=0),
        ),
    ]
