# Generated by Django 4.1.4 on 2023-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_order_quntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
