# Generated by Django 4.1.4 on 2023-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_quntity_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('cash', 'cash'), ('payment gatway', 'payment gatway')], default='cash', max_length=50),
        ),
    ]
